//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeMonitorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoilMoistureReading
    {
        public int Id { get; set; }
        public decimal MilliVolts { get; set; }
        public int SensorNumber { get; set; }
        public System.DateTime Taken { get; set; }
    }
}
